# Setup
title:               Patrick Schloss
tagline:             'Illustrator'
description:         'Illustrator, Character Designer, Visdev Artist, Jesus-Following Michigander, Unfunny Human'
url:                 https://patchschloss.github.io
baseurl:             ''
paginate:            
permalink:           pretty

# About/contact
author:
  name:              Patrick Schloss
  url:               https://patchschloss.github.io
  email:             pnschloss@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
# version:             1.1.0
google_analytics_id: #UA-XXXX-Y
